#!/usr/bin/expect -f
set timeout -1
set my_token "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"
spawn git push -u origin main
expect "Password for 'https://$my_token@github.com':"
send -- $my_token\r
expect eof
